services:
  minecraft:
    image: ghcr.io/alexandergg-0520/minecraft-server:runtime-jre25-gpu
    pull_policy: always
    container_name: mc-fabric

    ports:
      - "25565:25565"

    volumes:
      - minecraft_data:/data

    environment:
      EULA: "true"
      TYPE: "fabric"
      VERSION: "26.2"

      JVM_XMS: "1G"
      JVM_XMX: "4G"

      MAX_PLAYERS: "20"

      ENABLE_C2ME: "true"
      ENABLE_C2ME_HARDWARE_ACCELERATION: "true"
      I_KNOW_C2ME_IS_EXPERIMENTAL: "true"

      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"

    gpus: all

    networks:
      - minecraft_network

    restart: unless-stopped
    stop_grace_period: 240s
    mem_limit: 6g
    cpu_count: 2
    tty: true

volumes:
  minecraft_data:

networks:
  minecraft_network:
    driver: bridge
