apiVersion: v1
kind: Secret
metadata:
  name: minecraft-s3
  namespace: minecraft-paper-minio
type: Opaque
stringData:
  endpoint: https://minio.example.com
  access-key: replace-with-s3-access-key
  secret-key: replace-with-s3-secret-key
