#!/bin/bash
set -euo pipefail

log() { echo "[type-config] $*"; }

TYPE="${TYPE:-vanilla}"
DATA="/data"

log "Generating TYPE-specific config for TYPE=${TYPE}"

case "$TYPE" in

  paper)
    log "Generating Paper configuration files..."

    # -------------------------
    # paper-global.yml
    # -------------------------
    cat > "${DATA}/paper-global.yml" << 'EOF'
# Auto-generated by entrypoint
_ commented-out-example: |
  Edit /data/paper-global.yml if you want to customize.
settings:
  velocity-support:
    enabled: false
    online-mode: true
EOF

    # -------------------------
    # spigot.yml
    # -------------------------
    cat > "${DATA}/spigot.yml" << 'EOF'
settings:
  debug: false
world-settings:
  default:
    verbose: false
EOF

    # -------------------------
    # bukkit.yml
    # -------------------------
    cat > "${DATA}/bukkit.yml" << 'EOF'
settings:
  allow-end: true
spawn-limits:
  monsters: 70
EOF
    ;;

  fabric)
    log "Fabric: no extra global config required."
    # Fabric は config/* を mods が生成するため特別処理なし
    ;;

  forge | neoforge)
    log "Forge/NeoForge: config handled by mods, no global config needed."
    ;;

  vanilla)
    log "Vanilla: no extra config."
    ;;

  *)
    log "Unknown TYPE: ${TYPE}, skipping type config."
    ;;
esac

log "TYPE=${TYPE} configuration generation complete."
