services:
  minecraft:
    image: ghcr.io/alexandergg-0520/minecraft-server:runtime-jre21
    pull_policy: always

    ports:
      - "127.0.0.1:25565:25565"

    volumes:
      - minecraft_data:/data

    environment:
      EULA: "true"
      TYPE: "paper"
      VERSION: "1.21.8"
      JVM_XMS: "1G"
      JVM_XMX: "2G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "local-only-change-me"

    restart: unless-stopped
    stop_grace_period: 240s

volumes:
  minecraft_data:
