services:
  minecraft:
    image: ghcr.io/alexandergg-0520/minecraft-server:runtime-jre17
    pull_policy: always
    container_name: mc-forge

    ports:
      - "25565:25565"

    volumes:
      - minecraft_data:/data

    environment:
      EULA: "true"
      TYPE: "forge"
      VERSION: "1.20.1"

      JVM_XMS: "1G"
      JVM_XMX: "4G"

      MAX_PLAYERS: "20"

    networks:
      - minecraft_network

    restart: unless-stopped
    stop_grace_period: 240s
    mem_limit: 6g
    cpu_count: 2
    tty: true

volumes:
  minecraft_data:

networks:
  minecraft_network:
    driver: bridge
